name: ruff
version: 0.0.240
summary: An extremely fast Python linter, written in Rust.
# noinspection YAMLSchemaValidation
# https://youtrack.jetbrains.com/issue/PY-58754
description: |
  Ruff aims to be orders of magnitude faster than alternative tools while integrating more
  functionality behind a single, common interface.

  Ruff can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus a variety of plugins), [`isort`](https://pypi.org/project/isort/),
  [`pydocstyle`](https://pypi.org/project/pydocstyle/), [`yesqa`](https://github.com/asottile/yesqa),
  [`eradicate`](https://pypi.org/project/eradicate/), [`pyupgrade`](https://pypi.org/project/pyupgrade/),
  and [`autoflake`](https://pypi.org/project/autoflake/), all while executing tens or hundreds of
  times faster than any individual tool.

  Ruff goes beyond the responsibilities of a traditional linter, instead functioning as an advanced
  code transformation tool capable of upgrading type annotations, rewriting class definitions, sorting
  imports, and more.
  
  N.B. snap confinement: The snap package for ruff is limited by default to accessing files in your home directory.

confinement: strict
base: core22
# The base that the builds run on - allows building for other architectures
build-base: core22
# Performance difference with xz vs lzo is small in this case, but provides
# a ~40% reduction in file size for a very frequently updating snap.
compression: xz
contact: https://github.com/lengau/ruff/issues
issues:
  - https://github.com/lengau/ruff-snap/issues
  - https://github.com/charliermarsh/ruff/issues
source-code: https://github.com/charlier/ruff
website: https://github.com/charliermarsh/ruff
# This is essentially "build on any arch, for any arch"
architectures:
  - build-on: [amd64,i386,arm64,armhf,s390x,ppc64el]
    build-for: amd64
  - build-on: [amd64,i386,arm64,armhf,s390x,ppc64el]
    build-for: i386
  - build-on: [amd64,i386,arm64,armhf,s390x,ppc64el]
    build-for: arm64
  - build-on: [amd64,i386,arm64,armhf,s390x,ppc64el]
    build-for: armhf
  - build-on: [amd64,i386,arm64,armhf,s390x,ppc64el]
    build-for: s390x
  - build-on: [amd64,i386,arm64,armhf,s390x,ppc64el]
    build-for: ppc64el

# TODO: When ruff includes binaries in GitHub releases, switch to those.
parts:
  ruff:
    plugin: nil
    build-packages:
      - python3-pip
      - unzip
    override-pull: |
      export RUFF_VERSION=$(craftctl get version)
      craftctl default
      case "${CRAFT_TARGET_ARCH}" in
      amd64)
        export PIP_PLATFORM=manylinux2014_x86_64 
        ;;
      i386)
        export PIP_PLATFORM=manylinux2014_i686 
        ;;
      arm64)
        export PIP_PLATFORM=manylinux2014_aarch64 
        ;;
      ppc64el)
        export PIP_PLATFORM=manylinux2014_ppc64le 
        ;;
      armhf)
        export PIP_PLATFORM=manylinux2014_armv7l
        ;;
      *)
        export PIP_PLATFORM=manylinux2014_$CRAFT_TARGET_ARCH
        ;;
      esac
      # flake8-to-ruff doesn't get published at every release, so we
      # grab the latest version at or below the release version.
      pip3 download --only-binary=:all: "ruff==${RUFF_VERSION}" "flake8-to-ruff<=${RUFF_VERSION}"
    override-build: |
      craftctl default
      mkdir -p "${CRAFT_STAGE}/bin"
      unzip -j flake8_to_ruff*.whl '**/flake8-to-ruff' -d "${CRAFT_PART_INSTALL}/bin"
      unzip -j ruff*.whl '**/ruff' -d "${CRAFT_PART_INSTALL}/bin"
    stage:
      - bin/*
    prime:
      - bin/*
apps:
  ruff:
    command: bin/ruff
    plugs:
      - home
      - removable-media
  flake8-to-ruff:
    command: bin/flake8-to-ruff
    plugs:
      - home
      - removable-media
